/** Códigos estables de error de la API (Arquitectura §11.8). */
export const ERROR_CODES = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  IDENTITY_PROVIDER_ERROR: 'IDENTITY_PROVIDER_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  ENROLLMENT_NOT_ACTIVE: 'ENROLLMENT_NOT_ACTIVE',
  ENROLLMENT_ALREADY_EXISTS: 'ENROLLMENT_ALREADY_EXISTS',
  PROGRAM_NOT_AVAILABLE: 'PROGRAM_NOT_AVAILABLE',
  AGE_NOT_ALLOWED: 'AGE_NOT_ALLOWED',
  GUARDIAN_LINK_REQUIRED: 'GUARDIAN_LINK_REQUIRED',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  ASSENT_REQUIRED: 'ASSENT_REQUIRED',
  ZDR_REQUIRED: 'ZDR_REQUIRED',
  VOICE_QUOTA_EXCEEDED: 'VOICE_QUOTA_EXCEEDED',
  VOICE_SESSION_INVALID_STATE: 'VOICE_SESSION_INVALID_STATE',
  DIAGNOSTIC_ALREADY_COMPLETED: 'DIAGNOSTIC_ALREADY_COMPLETED',
  ACTIVITY_NOT_IN_LESSON: 'ACTIVITY_NOT_IN_LESSON',
  REVIEW_ALREADY_DECIDED: 'REVIEW_ALREADY_DECIDED',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiErrorShape {
  error: {
    code: ErrorCode;
    message: string;
    traceId?: string;
    details?: Record<string, unknown>;
  };
}
